### ISSUE TITLE
[EPIC] Allow greater parallelization of test executions

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#7291]
**Description**

We rely on forking to run our tests in parallel because we use a lot of static objects /shared memory. Not only can this lead to flakier tests, but it prevents us from fully utilizing all the resources we need to run in parallel. It also leads to strange patterns of testing where you have lots of small testing classes because only classes run in parallel, not methods. This then prevents running parameterized tests in parallel - if you have a parameterized test, where each case takes 10 seconds, and you have 10 cases, that's 100 seconds. There's no way to reduce it, or parallelize, since parameterized tests typically run in the same process. We could use threads to parallelize them, but then we run into issues with the `RecordingExporter` which is a shared, constant instance.

## Proposal

- Write all new tests such that they can be ran in parallel where applicable
- [ ] Decouple the record stream (e.g. `RecordStream`, `JobRecordStream`, etc.) from the `RecordingExporter`. Introduce an interface called `RecordStreamer` which has all of these transform methods as default, and only requires two methods which provide the base record streams. This allows us to decouple the exporter portion from the record stream itself, which will simplify using instances of the streams. See https://github.com/camunda-cloud/zeebe/issues/7504
- [ ] Modify all tests which use `RecordingExporter` to stream records from the relevant rule directly. This means, for example, an engine test using the `EngineRule` would call `engineRule.recordStream().deploymentRecords()` instead of `RecordingExporter.deploymentRecords()`. Same for `ClusteringRule`, `EmbeddedBrokerRule`, etc. This will help us to migrate to using test-specific (or class specific when the rule is used as a `@ClassRule`) record streams instead of the shared, constant model we use. Another option is to have the `EngineRule` (and others) implement `RecordStreamer` directly, and simply delegate the two methods to the underlying channel. Whatever feels best for the team (though I would most likely avoid that myself). This also means that the whole engine client has to be refactored to be given a `RecordStreamer` instance instead of just calling the `RecordingExporter`. https://github.com/camunda-cloud/zeebe/issues/7505
- [ ] Consider not using the exporter stuff/concept in the `EngineRule` and `StreamProcessorRule`, but actually have an implementation around the log stream reader interface. We can extract the "wait up to X seconds until a new record comes in" behavior of the `RecordIterator` from the `RecordingExporter` into a more generic `DelayedIterator` class; see below for a prototype.
- [ ] Introduce a `RecordChannel` class which is essentially the streaming portion/record accumulating portion of the `RecordingExporter`. Essentially all of it minus the exporter parts. This class uses no constant fields, just instance fields. The engine tests can simply create an instance of it and reuse it instead of the `RecordingExporter`. The `RecordingExporter` can still use a constant instance of this new class and delegate everything to it to help with the migration.
- [ ] Add a constant, concurrent map of ID -> `RecordChannel` in `RecordChannel`. This allows sharing the record channel across threads, such that the test thread can stream from it, and the exporter instance inside a broker can offer records to it. This means `RecordChannel` must be thread safe. The offer method should return a controllable position such that the test thread can acknowledge records if it wants (which could be by default just the offered record’s position).
- [ ] After this, start refactoring users of `RecordingExporter` to use the correct `RecordChannel`, i.e. test-specific or test-class if it's a class rule. Then drop the static part of the `RecordingExporter` such that only the `Exporter` part remain. Maybe rename it to `RecordChannelExporter` :smile: 

## Open questions

What's missing here is a way to deal with IPC - what if we want to stream things out of a container? There's currently no real way to deserialize a serialized `Record<?>` back into a `Record<?>` again. There's a community project which shows how to do it by serializing to JSON (see [zeebe-protocol-immutables](https://github.com/camunda-community-hub/zeebe-protocol-immutables)), and I have a prototype of an IPC exporter/receiver which uses Agrona's `ManyToOneRingBuffer` to export records, and a pair of `BroadcastReceiver` & `BroadcastTransmitter` to acknowledge them. It's fairly simple, but delegates the serialization/deserialization logic to the project I linked above. It could probably be simplified actually, but as a prototype:

<details><summary>DebugIpcExporter</summary>

```java
public final class DebugIpcExporter implements Exporter {
  private Logger logger;
  private Controller controller;
  private Config config;
  private boolean closed;

  private Path exportPath;
  private RingBuffer exportBuffer;

  private Path ackPath;
  private BroadcastReceiver ackReceiver;
  private ScheduledTask ackReceiveTask;
  private int ackConsumerId;

  @Override
  public void configure(final Context context) throws Exception {
    config = context.getConfiguration().instantiate(Config.class);

    exportPath = Path.of(config.exportPath);
    FileUtil.touch(exportPath);

    ackPath = Path.of(config.ackPath);
    FileUtil.touch(ackPath);

    logger = context.getLogger();
  }

  @Override
  public void open(final Controller controller) {
    this.controller = controller;

    exportBuffer =
        new ManyToOneRingBuffer(
            mapPath(exportPath, (256 * 1024 * 1024L) + RingBufferDescriptor.TRAILER_LENGTH));
    ackReceiver =
        new BroadcastReceiver(
            mapPath(ackPath, (256 * 1024 * 1024L) + BroadcastBufferDescriptor.TRAILER_LENGTH));
    ackReceiveTask = controller.scheduleCancellableTask(Duration.ofMillis(500), this::receiveAcks);
    ackConsumerId = -1;
  }

  @Override
  public void close() {
    closed = true;

    if (ackReceiveTask != null) {
      ackReceiveTask.cancel();
    }

    BufferUtil.free(exportBuffer.buffer());
    BufferUtil.free(ackReceiver.buffer());
  }

  @Override
  public void export(final Record<?> record) {
    if (ackConsumerId < 0) {
      ackConsumerId = record.getPartitionId();
    }

    final var serialized = record.toJson().getBytes(StandardCharsets.UTF_8);
    final var index = exportBuffer.tryClaim(ackConsumerId, serialized.length);
    if (index > 0) {
      try {
        exportBuffer.buffer().putBytes(index, serialized);
        exportBuffer.commit(index);
      } catch (final Exception e) {
        exportBuffer.abort(index);
        LangUtil.rethrowUnchecked(e);
      }
    }
  }

  private void receiveAcks() {
    // there's a race condition in Zeebe where a task may be cancelled but still be executed, so we
    // should protect against that here since closing the exporter would free the buffers, leading
    // to a segfault when we try to read from them
    if (closed) {
      return;
    }

    try {
      consumeAcks();
    } finally {
      ackReceiveTask =
          controller.scheduleCancellableTask(Duration.ofMillis(500), this::receiveAcks);
    }
  }

  private void consumeAcks() {
    if (ackConsumerId < 0) {
      logger.trace("Skip consuming acknowledgments until we know which partition we are");
      return;
    }

    long position = -1;
    for (int i = 0; i < config.maxAckConsumedCount && ackReceiver.receiveNext(); i++) {
      if (ackConsumerId == ackReceiver.typeId()) {
        position = ackReceiver.buffer().getLong(ackReceiver.offset(), ByteOrder.LITTLE_ENDIAN);
      }
    }

    if (position > 0) {
      controller.updateLastExportedRecordPosition(position);
    }
  }

  private AtomicBuffer mapPath(final Path path, final long size) {
    final var mappedBuffer =
        IoUtil.mapExistingFile(
            path.toFile(), MapMode.READ_WRITE, "debug IPC exporter buffer", 0, size);
    return new UnsafeBuffer(mappedBuffer);
  }

  @SuppressWarnings("java:S1104") // allow publicly visible members for this bean
  public static final class Config {
    public int maxAckConsumedCount = 10;

    public String exportPath;
    public String ackPath;
  }
}
```

</details>

<details><summary>DebugIpcReceiver</summary>

```java
public final class DebugIpcReceiver implements ControlledMessageHandler, AutoCloseable {
  private static final Logger LOGGER = LoggerFactory.getLogger(DebugIpcReceiver.class);
  private static final ObjectReader READER =
      new ObjectMapper().readerFor(new ImmutableRecordTypeReference<>());

  private final RingBuffer exportBuffer;
  private final BroadcastTransmitter ackTransmitter;
  private final Consumer<Record<?>> recordConsumer;
  private final ScheduledExecutorService executor;
  private final MutableDirectBuffer positionBuffer;

  public DebugIpcReceiver(
      final Path exportPath, final Path ackPath, final Consumer<Record<?>> recordConsumer) {
    this.exportBuffer =
        new ManyToOneRingBuffer(
            mapPath(exportPath, (256 * 1024 * 1024L) + RingBufferDescriptor.TRAILER_LENGTH));
    this.ackTransmitter =
        new BroadcastTransmitter(
            mapPath(ackPath, (256 * 1024 * 1024L) + BroadcastBufferDescriptor.TRAILER_LENGTH));
    this.recordConsumer = recordConsumer;

    this.executor = newExecutor();
    this.positionBuffer = new UnsafeBuffer(ByteBuffer.allocate(Long.BYTES));
  }

  public void start() {
    executor.schedule(this::consumeTask, 100, TimeUnit.MILLISECONDS);
  }

  @Override
  public void close() {
    executor.shutdownNow();
  }

  public synchronized void acknowledge(final int partitionId, final long position) {
    positionBuffer.putLong(0, position, ByteOrder.LITTLE_ENDIAN);
    ackTransmitter.transmit(partitionId, positionBuffer, 0, positionBuffer.capacity());
  }

  private void consumeTask() {
    try {
      consumeNewRecords();
    } finally {
      executor.schedule(this::consumeTask, 100, TimeUnit.MILLISECONDS);
    }
  }

  private void consumeNewRecords() {
    exportBuffer.controlledRead(this);
  }

  @Override
  public Action onMessage(
      final int msgTypeId, final MutableDirectBuffer buffer, final int index, final int length) {
    try (final var input = new DirectBufferInputStream(buffer, index, length)) {
      recordConsumer.accept(READER.readValue(input));
      return Action.COMMIT;
    } catch (final IOException e) {
      LOGGER.warn(
          "Failed to deserialize message on partition ID {}, closing receiver, no new records will be consumed",
          msgTypeId,
          e);
      close();
      return Action.BREAK;
    }
  }

  private AtomicBuffer mapPath(final Path path, final long size) {
    try {
      FileUtil.touch(path);
    } catch (final IOException e) {
      throw new UncheckedIOException(e);
    }

    final var mappedBuffer =
        IoUtil.mapExistingFile(
            path.toFile(), MapMode.READ_WRITE, "debug IPC exporter buffer", 0, size);
    return new UnsafeBuffer(mappedBuffer);
  }

  private ScheduledExecutorService newExecutor() {
    final RejectedExecutionHandler silentlyDiscardPolicy = new DiscardPolicy();
    final ThreadFactory threadFactory = r -> new Thread(r, "debug-ipc-exporter");

    return new ScheduledThreadPoolExecutor(1, threadFactory, silentlyDiscardPolicy);
  }
}
```

</details>

This is easily adapted with the `RecordChannel` and `RecordStreamer` concepts I outlined above.

## Additional context

<details><summary>DelayedIterator</summary>

```java
/**
 * An iterator which wraps another iterator, allowing for a small blocking delay when calling {@link
 * #hasNext()} if there is not yet a next element. If an element is produced while it's waiting,
 * then {@link #hasNext()} will return true. Use this to stream from asynchronous sources for
 * example.
 *
 * @param <T> the type of element returned by the underlying iterator
 */
public final class DelayedIterator<T> implements Iterator<T> {

  private final Iterator<T> delegate;
  private final Lock lock;
  private final Condition isEmptyCondition;
  private final long timeoutMs;

  public DelayedIterator(
      final Iterator<T> delegate,
      final Lock lock,
      final Condition isEmptyCondition,
      final Duration timeout) {
    this.delegate = delegate;
    this.lock = lock;
    this.isEmptyCondition = isEmptyCondition;

    timeoutMs = timeout.toMillis();
  }

  @Override
  public boolean hasNext() {
    lock.lock();

    try {
      final var deadline = Date.from(Instant.now().plusMillis(timeoutMs));
      var stillWaiting = true;

      while (!delegate.hasNext() && stillWaiting) {
        stillWaiting = isEmptyCondition.awaitUntil(deadline);
      }

      return delegate.hasNext();
    } catch (final InterruptedException e) {
      Thread.currentThread().interrupt();
      LangUtil.rethrowUnchecked(e);
    } finally {
      lock.unlock();
    }

    return false;
  }

  @Override
  public T next() {
    if (!delegate.hasNext()) {
      throw new NoSuchElementException();
    }

    return delegate.next();
  }
}
```

</details>

<details><summary>RecordChannel</summary>

```java
public final class RecordChannel implements RecordStreamer, Iterable<Record<?>> {

  private static final String DEFAULT_CHANNEL_ID = "default-record-channel";
  private static final ConcurrentMap<String, RecordChannel> CHANNELS = new ConcurrentHashMap<>();
  private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(5);

  private final List<Record<?>> records;
  private final DelayedIterator<Record<?>> iterator;

  private final Lock lock = new ReentrantLock();
  private final Condition isEmptyCondition = lock.newCondition();
  private final ConcurrentMap<Integer, Long> positions = new ConcurrentHashMap<>();

  private Duration timeout = DEFAULT_TIMEOUT;

  public RecordChannel() {
    this(new CopyOnWriteArrayList<>());
  }

  public RecordChannel(final List<Record<?>> records) {
    this.records = records;
    iterator = newIterator();
  }

  public static RecordChannel get(final String id) {
    return CHANNELS.computeIfAbsent(id, ignored -> new RecordChannel());
  }

  public static RecordChannel getDefault() {
    return get(getDefaultChannelId());
  }

  public static String getDefaultChannelId() {
    return DEFAULT_CHANNEL_ID;
  }

  public long offer(final Record<?> record) {
    lock.lock();

    try {
      records.add(record);
      isEmptyCondition.signalAll();
    } finally {
      lock.unlock();
    }

    return positions.getOrDefault(record.getPartitionId(), -1L);
  }

  public void acknowledge(final int partitionId, final long position) {
    positions.put(partitionId, position);
  }

  public RecordChannel setTimeout(final Duration timeout) {
    this.timeout = timeout;
    return this;
  }

  public RecordChannel reset() {
    lock.lock();

    try {
      records.clear();
      positions.clear();
      timeout = DEFAULT_TIMEOUT;
    } finally {
      lock.unlock();
    }

    return this;
  }

  public List<Record<?>> getRecords() {
    return records;
  }

  @Override
  @SuppressWarnings({"unchecked", "unused", "java:S1612"})
  public <T extends RecordValue> Stream<Record<T>> records(
      final ValueType valueType, final Class<T> valueClass) {
    return StreamSupport.stream(newSpliterator(), false)
        .filter(r -> r.getValueType() == valueType)
        .map(r -> (Record<T>) r);
  }

  @Override
  @SuppressWarnings({"unchecked", "java:S1612"})
  public RecordStream records() {
    return new RecordStream(
        StreamSupport.stream(newSpliterator(), false).map(r -> (Record<RecordValue>) r));
  }

  @Override
  public Iterator<Record<?>> iterator() {
    return iterator;
  }

  private Spliterator<Record<?>> newSpliterator() {
    return Spliterators.spliteratorUnknownSize(
        newIterator(), Spliterator.ORDERED | Spliterator.NONNULL);
  }

  private DelayedIterator<Record<?>> newIterator() {
    return new DelayedIterator<>(records.iterator(), lock, isEmptyCondition, timeout);
  }
}
```

</details>

**Comment by npepinpe** [comment]
I came across an issue related to logging. We typically use constant loggers, which are thread safe - however, they still all log to the same output. This isn't such a big issue in unit tests, but it's pretty important to have isolated logs as well for integration testing, especially when testing the distributed parts of the application. These distributed parts are much harder to test with traditional debuggers due to their asynchronous nature, so logs fill in the gaps when it comes to root causing issues. If the logs are all jumbled up, it's not particularly useful to run them in separate threads.

**Comment by npepinpe** [comment]
Other possible blockers: mocking static methods/classes, any kind of static registry which might get modified at runtime.
