### ISSUE TITLE
Add support for custom client command authorization

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#7490]
**Is your feature request related to a problem? Please describe.**
Zeebe currently does not provide support for client command authorization, which is a topic that has been requested multiple times (https://github.com/camunda-cloud/zeebe/issues/3942, https://forum.camunda.io/t/accessing-variables/1189/9, [SUPPORT-10694](https://jira.camunda.com/browse/SUPPORT-10694), etc). The [documentation](https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/security/authorization) states:
> Zeebe clients also provide a way for users to modify gRPC call headers, namely to contain access tokens. Note that the gateway doesn't provide any way of validating these headers, **users must implement a reverse proxy with a gRPC interceptor to validate them**.

**Describe the solution you'd like**
- Add support for users to provide **custom gRPC interceptors**. These can (among other use cases) be used to block requests on specific conditions, i.e. supports custom authorization for client commands.
- **Add RPCs to the broker to support queries for relevant data necessary to build a custom authorization interceptor**. These RPCs are only available to the gateway(s) and other brokers, so these will available from within the custom gRPC interceptors.

**Describe alternatives you've considered**
- multi-tenancy support (i.e. resource-based authorization support as a first-class citizen in Zeebe): will be a large and complex project to build-in to Zeebe, but in the long term I can image we'd need to build this. For now, let's offer something useful to our users that they can use until we work on multi-tenancy.
- offer a team-maintained reverse proxy that provides client command authorization: this comes with maintenance costs for the team (of course the proposed solution also comes with maintenance costs, but it is more flexible as it can be used for other things like custom caching, etc).

**Additional considerations**
- Note that using the new broker RPCs from within a gRPC interceptor **will add latency to the requests**.
- I think this should only be available to Camunda Cloud Self-Managed (i.e. so not in Camunda Cloud SaaS), in the same way that (and for the same reasons as to why) custom exporters are only available in Camunda Cloud Self-Managed.
- The RPCs are only an interim solution while full multi-tenant support is not yet implemented. Therefore, **these RPCs are not considered part of the public API** and will not receive the same semantic versioning treatment. They may be deprecated and removed in a minor version bump. I recommend keeping at least 1 minor version between deprecation and removal to allow users time to adapt.

**Comment by npepinpe** [comment]
ping @menski 

One thing to discuss is that this is an interim solution - it's quite clear that multi-tenancy is the right approach in the long term, not the broker-to-gateway RPCs, and we should also make it clear that these RPCs will go away (would be great to have a clear roadmap there, but don't hold your breath), and users can build on them with the caveat that they may get removed as part of a minor release.

**Comment by korthout** [comment]
@npepinpe Good point, I've added it as an additional consideration that the RPCs are not part of the public API

**Comment by korthout** [comment]
Today we discussed a bit on how to approach this topic.

I will start by describing some of the questions we want to find answers to. We can then perform a spike to find these answers. After that we can implement it with the knowledge gained from the spike. 

Some initial questions we have now:
- what will the Query API look like, e.g. should be similar to the Command API or can it be simpler?
- the Query API should be easy to remove, so how to keep it self-contained with the least invasion on existing code?
- how can the broker Query API gain access to the state?
- what will the server look like?
- how to best place this Query API behind a feature toggle?
- what should the interface to the Query API look like from within the interceptors?
- how to best allow users to provide custom gRPC interceptors?

**Comment by jwulf** [comment]
We would need to add some metadata to the gRPC calls in the clients, no? Would that be in the gRPC headers?

**Comment by npepinpe** [comment]
You can already add custom metadata to gRPC calls in the clients via the interceptors (or the dial options in the Go client). I'm not sure about unofficial clients though. If you want the OAuth token, that's already in the metadata under the key `Authorization` if you use the built-in `OAuthCredentialsProvider` - I imagine it works similarly with other clients.

**Comment by korthout** [comment]
Based on what we learned from the spike, I see the need for the following tasks:
- [ ] introduce a QueryService to `io.camunda.zeebe.engine.state` that implements 3 simple methods to retrieve the BpmnProcessId. Make it available by adding it as a deprecated parameter to the `PartitionListener` interface. It needs access to the ZeebeState, which it can easily get from the place where the partition listener interface is called, see dbc5cc1a0 as example 
- [ ] add request type to `io.camunda.zeebe.transport.ClientRequest`, that is used to set the topic name when sending requests to the broker. Make sure to set it to "command" for all existing commands, see 25c89a295, c5a5e0b42 and 37b25eb12  as examples
- [ ] introduce new SBE messages for `ExecuteQueryRequest` and `ExecuteQueryResponse`, see 67efc0a1b as example
- [ ] introduce a `QueryApiRequestHandler` to subscribe to the "event" topic, that uses the `ExecuteQueryRequestDecoder` to deserialize the query request and implements PartitionListener to gain access to the QueryService and respond to the request with the result. Based on a configuration option this api can be enabled or disabled.
- [ ] introduce a new gateway configuration for gRPC interceptors. They need to load a jar, load a class as `io.grpc.ServerInterceptor` and add this to the server builder (something like: `serverBuilder.intercept(interceptor)`). 
- [ ] introduce a Query API in the gateway that can be used to send `ExecuteQueryRequest` to the broker. Provide it to configured interceptors.
