### ISSUE TITLE
EPIC: Build state on Followers

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7492]
**Description**

I will use this issue to summarize what has been done and what needs to be done in order to implement the ZEP https://github.com/zeebe-io/enhancements/blob/master/ZEP007-build-state-on-followers.md. 

I did a POC regarding the ZEP you can find the summary here https://github.com/camunda-cloud/zeebe/issues/7328#issuecomment-868503971 related branch https://github.com/camunda-cloud/zeebe/commits/zell-7328-poc-state-on-followers

ToDo's:

- [X] New Metric for Leader Failover https://github.com/camunda-cloud/zeebe/issues/7433
- [x] Replay
  - [X] Implement replay of ErrorEvents https://github.com/camunda-cloud/zeebe/issues/7429
    - [X] Blacklist state needs to be adjusted https://github.com/camunda-cloud/zeebe/issues/7428
  - [X] Write a ReplayStateMachine, which does replay until the end of the log. https://github.com/camunda-cloud/zeebe/issues/7430
  - [X] Replace the ReprocessingStateMachine
  - [x] Support continuously Replay in the ReplayStateMachine https://github.com/camunda-cloud/zeebe/issues/7457
    - [x] Adjust StreamProcessor such it starts either in replay or processing (with replay in the beginning) mode
    - [x] [ReplayStateMachine can be paused/resumed](https://github.com/camunda-cloud/zeebe/commit/375733d3a51ad2d10157fc1786486180ff2e219d) https://github.com/camunda-cloud/zeebe/issues/7512
- [x] Snapshots on Followers
  - [x] Follower don't need to wait for commit in order to mark snapshot as valid https://github.com/camunda-cloud/zeebe/issues/7510
  - [x] [StreamProcessor returns last replayed pos if on cont replay (used for snapshots)](https://github.com/camunda-cloud/zeebe/commit/5478a3efa83ecb324b647bd2934f680bec1605ee) https://github.com/camunda-cloud/zeebe/issues/7511
- [X] Commit Listeners in LogStream
  - [X] Rework Logstream listeners, remove commit  https://github.com/camunda-cloud/zeebe/issues/7454 
  - [X] Remove get commit from logstream https://github.com/camunda-cloud/zeebe/issues/7453
  - [X] Rewrite commit listeners in LogStream, should use the Raft commit listeners https://github.com/camunda-cloud/zeebe/issues/7455
    - [X] allow to listener for new records on followers as well
- [x] Exporters:
  - [x] Prepare ExporterPositions SBE message https://github.com/camunda-cloud/zeebe/issues/7478
  - [x] Send positions regularly from ExporterDirector https://github.com/camunda-cloud/zeebe/issues/7479
  - [x] Implement new ExporterService which consumes SBE messages and updates Exporter positions in the state https://github.com/camunda-cloud/zeebe/issues/7480
- [x] State On Followers
  - [x] Build State on Followers https://github.com/camunda-cloud/zeebe/issues/7513
  - [x] [Extract Bootstrap steps and Follower/Leader/Transition Steps](https://github.com/camunda-cloud/zeebe/commit/7aa7b761182e1aa3dfc36b3e8f3aed6da34dd3c1) https://github.com/camunda-cloud/zeebe/issues/7514
  - [x] Improve Leader-Follower transition https://github.com/camunda-cloud/zeebe/issues/7515
  - [x] Handle Install Request https://github.com/camunda-cloud/zeebe/issues/7481
- [x] Tests https://github.com/camunda-cloud/zeebe/issues/7696
  - [x] Benchmark: Run the last release as base against the version with all changes and observe leader changes and the new added metric. The Leader start to process time should be lower.
  - [x] State is build on Followers
  - [x] **Same** State is build on Leader AND Followers
  - [x] Followers can take snapshots and compact their logs
  - [x] Fail-over still works
  - [x] After fail-over the new Leader should be able to export after the last lowest exporter position. https://github.com/camunda-cloud/zeebe/issues/7731
  - [x] After fail-over the new Leader should be able to process after the last processed command.
  - [x] We can handle InstallRequests on Followers
- [x] Misc
  - [x] Remove Snapshot replication
  - [x] Add ReplayStateMachine Class Doc https://github.com/camunda-cloud/zeebe/issues/7476
  - [x] Move reader reset out of ReplayStateMachine https://github.com/camunda-cloud/zeebe/issues/7477
 

I will keep that updated and try to add a summary to make hand over easier.

**Comment by Zelldon** [comment]
### Handover

Hey Friends,

the last two days have been a bit rough and wild, but I tried to break it down as best as I could.

One issue might be a bit bigger (https://github.com/camunda-cloud/zeebe/issues/7513), but I didn't wanted to interfere too much in your work and was not 100% sure since there will be lot of inter-dependencies. Just try it out I would say.

As you can see above, there is a kind of an Todo-list, where all issues are also linked. You can work on them from Top-To-Bottom, I would say. I already assigned some issues to you.

For example (as discussed) I thought @deepthidevaki could start with https://github.com/camunda-cloud/zeebe/issues/7481 to think and verify whether handling the InstallRequest like described in the ZEP works. I think this could probably already implemented without issues, before really building the state on followers.

I would like that @saig0 could take a look at my last PR's, and take them over. This would mean adjust to your needs and fix open issues if there any (I hope not). Then I would suggest to work on the SnapshotDirector https://github.com/camunda-cloud/zeebe/issues/7510, since this is a component we need for building state on Followers. Be aware that you have to solve first https://github.com/camunda-cloud/zeebe/issues/7511. There is another small issue regarding the ReplayStateMachine, which should be an easy pick https://github.com/camunda-cloud/zeebe/issues/7512. 

Be aware before your start with https://github.com/camunda-cloud/zeebe/issues/7513 the following issues need to be resolved:

* #7510
* #7457
* #7480
* #7481 (might be optional)

After you have build the state on followers you can work on improving the transition time from Follower-To-Leader https://github.com/camunda-cloud/zeebe/issues/7515. First this would mean extract components, which should be long-living (https://github.com/camunda-cloud/zeebe/issues/7514) and components/services which need to be reset etc. 

For further information please take a look at the [ZEP](https://github.com/zeebe-io/enhancements/blob/master/ZEP007-build-state-on-followers.md#switch-to-leader-partition) or the [POC](https://github.com/camunda-cloud/zeebe/blob/zell-7328-poc-state-on-followers/broker/src/main/java/io/camunda/zeebe/broker/Broker.java), which I hope should help here as well. If there is anything blocking don't hesitant to reference me in a comment, I will answer in a timely manner :)

I hope that helps you to work on this issue and I looking forward to the results! See you soon :wave:

**Comment by Zelldon** [comment]
The implementation of building state on Followers is done, big thanks goes out to @deepthidevaki and @saig0 :hugs: :bow:
