### ISSUE TITLE
[Epic] Support user task assignee & candidate groups

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#8020]
**Is your feature request related to a problem? Please describe.**
As a user I would like to specify task assignee and/or candidate-groups for user tasks.

**Describe the solution you'd like**
A user should be able to define the user task assignee and candidate-groups in BPMN, as custom extension elements.

Both attributes should allow to set static values, i.e. the user id or group name, and expressions to compute the values during process execution.

Tasklist should respect the value of the assignee and already assign the task to the specified user id. The candidate-groups attribute is not visible in the Tasklist UI, but should be a part of the API query parameters and response value.

**Describe alternatives you've considered**
Supporting the BPMN spec-compliant `humanPerformer` and `potentialOwner` instead (or next to) the custom extension elements (assignee and candidate-groups). However, this leads to more complex xml and less flexibility for Zeebe.

Not supporting the spec, nor custom extensions, but instead using input mappings to specify the assignee and candidate-groups directly. Zeebe currently already supports this. Since we want to use job headers to communicate the properties to Tasklist, it does not make sense to support this now.

Not supporting the spec, nor custom extensions, but instead using headers to specify the assignee and candidate-groups directly. Although Zeebe currently already supports this, it does not (yet) support expression evaluation for task headers. We do not see a reason to support this now.

**Additional context** 
See Camunda Platform docs about this feature https://docs.camunda.org/manual/7.16/reference/bpmn20/tasks/user-task/#user-assignment which supports even more features.

## Issue tracking
- [x] https://github.com/camunda-cloud/zeebe/issues/8053
- [x] https://github.com/camunda-cloud/zeebe/issues/8054
- [x] https://github.com/camunda-cloud/zeebe/issues/8055
- [x] https://github.com/camunda/camunda-modeler/issues/2535
- [x] https://github.com/camunda-cloud/tasklist/issues/1439
- [x] https://github.com/camunda-cloud/camunda-cloud-documentation/issues/454
