### ISSUE TITLE
Deprecate `zeebe-test`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8143]
**Description**
We want to deprecate and later remove the `zeebe-test` module. We will annotate all public types in this module with `@Deprecated` and announce the deprecation for `1.3.0` and remove the module in `1.4.0`. 

**Reasoning**
`zeebe-test` exposes a lot of zeebe internals, such as the `zeebe-broker` module, which is not ideal for a number of reasons. 

* It is currently blocking us from upgrading internal modules to use Java 17
* It makes breaking changes to internal modules impossible

There are alternatives such as [zeebe-test-container](https://github.com/camunda-community-hub/zeebe-test-container) and [eze](https://github.com/camunda-community-hub/eze) as well as [camunda-cloud-testing](https://github.com/camunda-cloud/camunda-cloud-testing) which will be available in the near future.

**Impact**
There are a number of projects currently relying on `zeebe-test`:
* [ ] [zeebe-test-template](https://github.com/zeebe-io/zeebe-test-template-java/issues/5)
* [ ] [zeebe-hazelcast-exporter](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/issues/141)
* [ ] [zeebe-kafka-exporter](https://github.com/camunda-community-hub/zeebe-kafka-exporter/issues/231)
* [ ] [zeebe-csv-exporter](https://github.com/zeebe-io/zeebe-csv-exporter/issues/7)
* [x] [spring-zeebe](https://github.com/camunda-community-hub/spring-zeebe/issues/133)

The deprecation period gives enough time to either deprecate these projects (for example in the case of `zeebe-test-template`) or transition them to use a different testing approach.

Camunda internal projects such as Optimize and Operate have already started their migration from `zeebe-test` to `zeebe-test-container`. Zeebe internal usages of `zeebe-test`, for example some integration tests,  will continue to be supported by moving some of the code from `zeebe-test` to `zeebe-test-util` which is not meant to be used outside of the zeebe project.

**Timeline**
Deprecate for `1.3.0-alpha2`, first stable version with deprecated `zeebe-test` is `1.3.0`
Remove for `1.4.0-alpha1`, first stable version with removed `zeebe-test` is `1.4.0`

**Comment by npepinpe** [comment]
You can ignore zeebe-kafka-exporter, I'll deal with it :smile:

**Comment by menski** [comment]
@oleschoenburg let's create issues in the projects which still use zeebe-test and then we can close this issue, there is not much more we can do on Zeebe side
